### ISSUE TITLE
Not working with 2021.3.25f1?

### ISSUE THREAD

**Issue by ansorre** [mminer/big-image-recorder#1]
All tiles are transparent!

**Comment by mminer** [comment]
I tried a sample scene on 2021.3.25 but can't reproduce the problem you're seeing. Are you able to create a regular image sequence with Recorder?

**Comment by mminer** [comment]
I ran into a scenario where I entered a camera tag in the Recorder UI, but no camera in the scene was assigned that tag. In this case the recorder produces transparent tiles like you describe. Could this be the problem you ran into?

I added better error checking in the latest release (v1.0.1) that catches this problem. With any luck it'll fix your issue (but feel free to reopen this if you keep seeing the same result).
