### ISSUE TITLE
Crash when generating tiles for very large image

### ISSUE THREAD

**Issue by LucyBW1** [mminer/big-image-recorder#2]
Unity consistently crashes while using BigImageRecorder to generate tiles for this resolution: 180,000 x 36,000.
3 rows x 12 collumns. Unity crashes around image_2-6, after about 8 to 11 mins of tile recording.
I am using Unity2019.4.
I upgraded the UnityRecorder to latest, but still crashes.
I tried different scenes - still crashes for this high resolution.
Worked great for lower resolutions: 120,000 x 24,000 and less.

This tool is so useful - I really appreciate you making it available!
Do you have any insight? Happy to provide errorlog...

**Comment by mminer** [comment]
My hunch is that it runs out of memory, but let me dig into this a bit. In the meantime an error log would be lovely.

**Comment by LucyBW1** [comment]
Thanks so much for having a look at it!
I'm curious if it happens for you.

I have attached an error log.
It always happens somewhere in EncodeToPng()

ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid
address.' (Address: 00007FF79F1C31D4)
0x00007FF79F1C31D4 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid
address.' (Address: 00007FF79F1C41B5)
0x00007FF79F1C41B5 (Unity) (function-name not available)
0x0000015CADD461FE (UnityEngine.ImageConversionModule)
UnityEngine.ImageConversion.EncodeToPNG()
0x0000015CADD44E93 (BigImageRecorder.Editor)
UnityEditor.BigImageRecorder.BigImageRecorder.WriteImageTiles()
0x0000015CADD4491B (BigImageRecorder.Editor)
UnityEditor.BigImageRecorder.BigImageRecorder.RecordFrame()
0x0000015CADD40E50 (Unity.Recorder.Editor)
UnityEditor.Recorder.RecordingSession.RecordFrame()
0x0000015CADD400EB (Unity.Recorder.Editor)
UnityEditor.Recorder.RecorderComponent.FrameReady()


The errorlog always looks like this. Always after 10 or 11 or 12 minutes.
On different tiles of the image I am rendering.

Btw, I fixed an issue in BigImageRecorderSettings.cs (in my local
BigImageRecorder).
Stitching failed when my tiles went double digits. Had to format the tile
filenames with "D2" so that tile numbering used double digits, or else the
stitching would stitch tiles in the wrong order.

        public BigImageRecorderSettings()
        {
            FileNameGenerator.AddWildcard(rowsWildcard, session =>
                (session?.recorder as
BigImageRecorder)?.Input.InputSettings.Rows.ToString("D2") ?? "0"); //LBW
added "D2"

            FileNameGenerator.AddWildcard(columnsWildcard, session =>
                (session?.recorder as
BigImageRecorder)?.Input.InputSettings.Columns.ToString("D2") ?? "0");
//LBW added "D2"

            FileNameGenerator.AddWildcard(tileRowWildcard, session =>
                (session?.recorder as
BigImageRecorder)?.RowBeingWritten.ToString("D2") ?? "0"); //LBW added "D2"

            FileNameGenerator.AddWildcard(tileColumnWildcard, session =>
                (session?.recorder as
BigImageRecorder)?.ColumnBeingWritten.ToString("D2") ?? "0"); //LBW added
"D2"

            FileNameGenerator.FileName =
$"image_{DefaultWildcard.Frame}_{tileRowWildcard}-{tileColumnWildcard}";
        }

Thanks!
Lucy

**Comment by mminer** [comment]
I haven't had great luck reproducing the crash, but perhaps I haven't let it run long enough. The stack trace with `EncodeToPNG` makes me think that my out-of-memory hunch was right. I made some optimizations in the latest version that should help. Could you give it a try and let me know if it still crashes for you?

Also, good tip about using double digits for the rows/columns in the filename. I pushed that change in 20acbaafd88ba0893a68e3084b222ec99ea12b02.

**Comment by LucyBW1** [comment]
Ok - I'll give it a shot. Thanks!

**Comment by LucyBW1** [comment]
It worked at my high resolution (180,000 x 36,000) on 2 different scenes! Amazing :-)
And I am using ImageMagick for the stitching, as you recommend. Also works great.
Thank you so much - this tool is really helpful.

**Comment by mminer** [comment]
Wonderful, thanks for verifying. I'm glad to hear the tool is useful.
